### ISSUE TITLE
Unattended Connections

### ISSUE THREAD

**Issue by jbedgood** [miroslavpejic85/p2p#10]
Is there a possible way to set this up so that its more teamviewer like in the way that once the product is installed you can connect to a PC without having live interactions with the far end computer. This would then make it a very good substitution for teamviewer.

**Comment by CompuRoot** [comment]
@jbedgood 

This will bring Pros & Cons:
- **Pros:** You already described it.
- **Cons:** Since most of residential IP are dynamic then you have to have to manage somehow association between IP and real computer, so you would need some unique ID for computers that must be managed with some centralized  solution to avoid names clashing or use some kind of DHT chatty protocols, which both will void privacy and will bring dependency

**Comment by TheColonel2688** [comment]
So since this was closed is this a "no" on this feature?

**Comment by miroslavpejic85** [comment]
@TheColonel2688,
The idea was to be a portable app, which doesn't need any installation or configuration.
In case, you can try this one: https://www.pocketsolution.net/

**Comment by CompuRoot** [comment]
>  In case, you can try this one: https://www.pocketsolution.net/
I tried free versions, but the only text chat is working. (Windows7 <=> JRDS on Linux)
Also, what is the reason to require app to work under administrative account on windows ?
