### ISSUE TITLE
Two nodes cannot connect to each other and are not on the same LAN. Why?

### ISSUE THREAD

**Issue by Haoke98** [miroslavpejic85/p2p#55]
Point1: 
OS: Windows10
![截屏2024-01-29 16 19 44](https://github.com/miroslavpejic85/p2p/assets/55436234/3a644fc1-ba4a-4863-a111-f71c5f9e72f1)
![截屏2024-01-29 16 21 40](https://github.com/miroslavpejic85/p2p/assets/55436234/8c86f0b5-11dd-40b0-b3b8-af9eb8eadaa1)

Point2:
OS: Windows2016 Server
![截屏2024-01-29 16 20 49](https://github.com/miroslavpejic85/p2p/assets/55436234/fa15e8db-db87-4005-b5f9-0d233ded0f3f)
![截屏2024-01-29 16 21 40](https://github.com/miroslavpejic85/p2p/assets/55436234/8c86f0b5-11dd-40b0-b3b8-af9eb8eadaa1)

**Comment by miroslavpejic85** [comment]
The issue arises because the `two nodes are not on the same Local Area Network` (LAN). For two devices to communicate directly within a LAN, they must be part of the same network segment and share the same subnet. Since these nodes are on different LANs, they cannot connect directly. To `establish a connection` between them, you should `use a Wide Area Network (WAN) option`.
